#!/usr/bin/env python3
"""Compile newsletter/*.md into worker/newsletter-content.js.

The generated file's own header says "Do not edit this file manually" — this is
the generator that makes that instruction true. It was missing from the repo, so
the only options were to hand-edit the file that forbids hand-editing, or to
rebuild it from memory each issue.

Language comes from the filename: foo.es.md -> es, foo.md -> en.
Backups (*.before-edit-*, *.backup-*) are ignored; they are gitignored anyway.

Usage:
    python3 newsletter/build.py            # write worker/newsletter-content.js
    python3 newsletter/build.py --check    # exit 1 if the file is out of date
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "newsletter"
OUT = ROOT / "worker" / "newsletter-content.js"

HEADER = (
    "// Generated from newsletter Markdown files.\n"
    "// Do not edit this file manually.\n"
    "\n"
    "export const NEWSLETTERS = "
)

# Only these reach the Worker. `status:` is a drafting note and is deliberately
# dropped — it must never ride along into a sent email.
FIELDS = ("issue", "date", "subject", "preheader")


def parse(path):
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not match:
        sys.exit("%s: missing --- frontmatter block" % path.name)

    meta = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        # Frontmatter values may be quoted because they contain a colon.
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value

    missing = [f for f in FIELDS if not meta.get(f)]
    if missing:
        sys.exit("%s: frontmatter missing %s" % (path.name, ", ".join(missing)))

    body = match.group(2).strip()
    if "{{unsubscribe_url}}" not in body:
        sys.exit(
            "%s: no {{unsubscribe_url}} placeholder. Every issue must carry an "
            "unsubscribe link — sending without one breaks CAN-SPAM and gets the "
            "domain marked as spam." % path.name
        )

    out = {f: meta[f] for f in FIELDS}
    out["markdown"] = body
    return out


def collect():
    sources = sorted(
        p for p in SRC_DIR.glob("*.md")
        if ".before-edit-" not in p.name and ".backup-" not in p.name
    )
    if not sources:
        sys.exit("no newsletter markdown found in %s" % SRC_DIR)

    issues = {}
    for path in sources:
        lang = "es" if path.name.endswith(".es.md") else "en"
        if lang in issues:
            sys.exit("two %s sources: %s and %s" % (lang, issues[lang][0], path.name))
        issues[lang] = (path.name, parse(path))

    if "en" not in issues:
        sys.exit("no English source (a file not ending in .es.md)")

    # The broadcast picks content by language but is told the issue number
    # separately. If the two languages disagree, half the list gets the wrong
    # issue under the right idempotency marker, and nothing reports an error.
    numbers = {lang: data["issue"] for lang, (_, data) in issues.items()}
    if len(set(numbers.values())) > 1:
        sys.exit("issue numbers disagree across languages: %s" % numbers)

    return {lang: data for lang, (_, data) in sorted(issues.items())}


def render(data):
    return HEADER + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"


def main():
    rendered = render(collect())
    check = "--check" in sys.argv

    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if current == rendered:
        print("newsletter-content.js is up to date")
        return 0

    if check:
        print("newsletter-content.js is STALE — run: python3 newsletter/build.py")
        print("Deploying without rebuilding sends the previously compiled issue.")
        return 1

    OUT.write_text(rendered, encoding="utf-8")
    print("wrote %s" % OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
